-- Add V3 Enrichment Columns
ALTER TABLE tools 
ADD COLUMN IF NOT EXISTS tagline VARCHAR(500),
ADD COLUMN IF NOT EXISTS pricing_model VARCHAR(20) CHECK (pricing_model IN ('free', 'freemium', 'paid', 'contact', 'open-source')),
ADD COLUMN IF NOT EXISTS price_amount DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS price_currency VARCHAR(3) DEFAULT 'USD',
ADD COLUMN IF NOT EXISTS has_free_tier BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS has_trial BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS trial_days INTEGER,
ADD COLUMN IF NOT EXISTS tags TEXT[],
ADD COLUMN IF NOT EXISTS use_cases TEXT[],
ADD COLUMN IF NOT EXISTS features TEXT[],
ADD COLUMN IF NOT EXISTS target_audience TEXT[],
ADD COLUMN IF NOT EXISTS operating_system TEXT[],
ADD COLUMN IF NOT EXISTS platforms TEXT[],
ADD COLUMN IF NOT EXISTS skill_level VARCHAR(20) CHECK (skill_level IN ('beginner', 'intermediate', 'advanced', 'expert', 'all')),
ADD COLUMN IF NOT EXISTS learning_curve VARCHAR(20) CHECK (learning_curve IN ('easy', 'moderate', 'steep')),
ADD COLUMN IF NOT EXISTS documentation_quality VARCHAR(20) CHECK (documentation_quality IN ('excellent', 'good', 'fair', 'poor', 'none')),
ADD COLUMN IF NOT EXISTS support_options TEXT[],
ADD COLUMN IF NOT EXISTS api_available BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS integrations TEXT[],
ADD COLUMN IF NOT EXISTS alternatives TEXT[],
ADD COLUMN IF NOT EXISTS pros TEXT[],
ADD COLUMN IF NOT EXISTS cons TEXT[],
ADD COLUMN IF NOT EXISTS best_for TEXT,
ADD COLUMN IF NOT EXISTS not_recommended_for TEXT,
ADD COLUMN IF NOT EXISTS verdict TEXT,
ADD COLUMN IF NOT EXISTS company_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS company_founded INTEGER,
ADD COLUMN IF NOT EXISTS employee_count VARCHAR(20),
ADD COLUMN IF NOT EXISTS funding_raised VARCHAR(50),
ADD COLUMN IF NOT EXISTS notable_customers TEXT[],
ADD COLUMN IF NOT EXISTS has_privacy_policy BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS gdpr_compliant BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS security_features TEXT[],
ADD COLUMN IF NOT EXISTS update_frequency VARCHAR(20) CHECK (update_frequency IN ('daily', 'weekly', 'monthly', 'quarterly', 'yearly', 'unknown')),
ADD COLUMN IF NOT EXISTS transparency_score INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS experience_score DECIMAL(2,1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS enrichment_status VARCHAR(20) DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS ai_data JSONB;

-- Update status for existing tools
UPDATE tools SET enrichment_status = 'pending' WHERE enrichment_status IS NULL;
